name: .NET Framework

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022    # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore Packages
      run: nuget restore "FM Tracker.sln"

    - name: Build debug
      run: msbuild "FM Tracker.sln" -t:rebuild -property:Configuration=Debug

    - name: Build release
      run: msbuild "FM Tracker.sln" -t:rebuild -property:Configuration=Release
      
    - name: Upload debug
      uses: actions/upload-artifact@v4
      with:
        name: win-debug-${{ github.sha }}
        path: FM Tracker\bin\Debug
        
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: win-release-${{ github.sha }}
        path: FM Tracker\bin\Release
