name: .NET Framework

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-2022    # works fine lol

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore Packages
      run: nuget restore "FM Tracker.sln"

    - name: Build debug
      run: msbuild "FM Tracker.sln" -t:rebuild -property:Configuration=Debug

    - name: Build release
      run: msbuild "FM Tracker.sln" -t:rebuild -property:Configuration=Release
      
    - name: Upload debug
      uses: actions/upload-artifact@v4
      with:
        name: win-debug-${{ github.sha }}
        path: FM Tracker\bin\Debug
        
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: win-release-${{ github.sha }}
        path: FM Tracker\bin\Release

    - name: Zip Debug
      run: Compress-Archive -Path "FM Tracker/bin/Debug/*" -DestinationPath win-debug.zip

    - name: Zip Release
      run: Compress-Archive -Path "FM Tracker/bin/Release/*" -DestinationPath win-release.zip

    - name: Create or Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: dev
        name: Nightly build
        prerelease: false
        overwrite_files: true
        body: |
          Automatic build from commit ${{ github.sha }}
          This will not be marked as prerelease as I will not be making an actual release anytime soon.
        files: |
          win-debug.zip
          win-release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
